[workspace]
# Enable changelog generation for all packages
changelog_update = true
# Enable git tag creation
git_tag_enable = true
# Tag name format
git_tag_name = "{{package}}-v{{version}}"
# Disable GitHub/GitLab release creation
git_release_enable = false
# Allow dirty working directory for testing
allow_dirty = true
# Dependencies update strategy
dependencies_update = true
# Publish to crates.io (disabled for testing)
publish = false
# PR settings
pr_name = "chore: release {{package}} v{{version}}"
pr_draft = false

# Package-specific configurations
[[package]]
name = "release-test-core"
# Changelog path relative to crate directory
changelog_path = "CHANGELOG.md"

[[package]]
name = "release-test-utils"
changelog_path = "CHANGELOG.md"

[[package]]
name = "release-test-cli"
changelog_path = "CHANGELOG.md"
# CLI package might want different versioning strategy
semver_check = true